#!/bin/bash


#############################################
#> https://github.com/vinodnimbalkar/mxplayer
#############################################

if [[ $1 == *"live-tv"* ]]
then
    response=$(curl -s $1 | sed 's/\"https:\/\/llvod\.mxplay\.com\/\"/\n/g' | sed 's/"},"/\n/g' | grep -Eo '(https:\/\/mxlook-content\.akamaized.net/v1/master).*(master\.m3u8)' | head -n 1)
    mpv $response
else
    response=$(curl -s $1 | tr "," "\n" | grep -E '(^\"contentUrl\":\"https:\/\/media-content\.akamaized\.net\/video).*(.m3u8)' | cut -d '"' -f 4)
    echo $response
    mpv "${response}"
fi
